<section class="characterPage">
    <div class="characterPageDesc">
        <h1>Listes des personnages de la guilde Fairy tail</h1>
        <p>Cette page est uniquement sur les membres de la guilde de Fairy tail
            et non sur TOUT les personnages du monde.</p>
        <p>Pour avoir la biography d'un personnage, cliquez sur son nom !</p>
    </div>
    <div class="characterList">
        <?php foreach ($characters as $character): ?>
            <div class="character">
                <img src="<?= $character['photo'] ?>" alt="Photo de <?= htmlspecialchars($character['characterName']) ?>">
                <a href="characterDetails.php?characterId=<?= intval($character['characterId']) ?>">
                    <?= htmlspecialchars($character['characterName']) ?>
                </a>
            </div>
        <?php endforeach ?>
    </div>
</section>