<footer>
    <h3>Source <a href="https://fr.wikipedia.org/wiki/Fairy_Tail" target="_blank">Wikipédia</a></h3>
    <nav>
        <ul>
            <li>
                <a href="<?= PATH_URI?><?= "index.php"?>">La Guilde</a>
            </li>
            <li>
                <a href="<?= PATH_URI?><?= "charactersList.php"?>">Rechercher un membre</a>
            </li>
        </ul>
        <p>© copyright par Thierry PADILLA et FAN de Fairy Tail</p>
</footer>
