<header>
    <a href="<?= PATH_URI?><?="index.php"?>"><img src="<?= PATH_URI ?>public/images/titleFairyTail.svg?>" alt="Titre de la guilde"></a>
    <nav>
        <ul>
            <li>
                <a href="<?= PATH_URI?><?="index.php"?>"><i class="fa fa-home"></i>La Guilde</a>
            </li>
            <li>
                <a href="<?= PATH_URI?><?= "charactersList.php"?>"><i class="fa fa-list"></i>Listes des membres</a>
            </li>
        </ul>
    </nav>
</header>