<main>
    <h1>
        <img src="<?= PATH_URI ?>public/images/fairy-tail-logo-png-7-transparent.png"
             alt="Logo SVG de la guilde Fairy Tail">
        La Guilde De Fairy Tail !
        <img src="<?= PATH_URI ?>public/images/fairy-tail-logo-png-7-transparent.png"
             alt="Logo SVG de la guilde Fairy Tail">
    </h1>
    <section class="introductionPrimary">
        <article class="guildIntroductionReal">
            <h2>Présentation Reel</h2>
            <p>Fairy Tail (littéralement « Queue de fée ») est un shōnen manga écrit et
                dessiné par Hiro Mashima. Il est prépublié dans l’hebdomadaire Weekly Shōnen Magazine de l’éditeur
                Kōdansha
                entre le 2 août 2006 et le 27 juillet 2017 au Japon, et est compilé en un total de soixante-trois
                tomes.
                En France, en Suisse romande et en Belgique, le manga est publié en intégralité par Pika Édition
                entre
                le
                10 septembre 2008 et le 27 juin 2018.
                Face au succès, le manga a été adapté en anime avec une série télévisée d’animation de 328 épisodes
                diffusées
                de octobre 2009 à septembre 2019, neuf OAV et deux films d’animation sortis par les studios A-1
                Pictures,
                Satelight et Bridge au Japon. En France, l’anime est diffusé depuis le 3 juin 2011 sur Game One1 et
                depuis
                le 28 janvier 2012 sur Direct Star2 puis D173. Au Québec, l’anime est disponible en VOD sur la
                plate-forme
                Illico télé numérique de Vidéotron depuis 2012. </p>
        </article>
        <article class="guildIntroductionInUnivers">
            <h2>Présentation Dans l'Univers de Fairy Tail</h2>
            <p>Dans le royaume de Fiore, il existe parmi le commun des mortels des hommes et des femmes qui
                manipulent
                la magie : ils sont appelés mages. Pour mieux les contrôler, des guildes — endroits où les mages se
                réunissent
                et font des travaux afin de gagner des joyaux (monnaie de Fiore) — ont été créées et mises sous la
                responsabilité du conseil de la magie (par l’intermédiaire des maîtres de guildes).

                Outre la nécessité de contrôler des mages, ce réseau a d’autres utilités. En effet,
                il permet de fournir un large choix de mages au client, et de nombreuses missions aux mages par le
                biais de petites annonces.

                Parmi les nombreuses guildes, une d’entre elles fait particulièrement parler d’elle,
                que ce soit par les actes réalisés par ses membres, mais aussi et surtout pour les dégâts matériels
                provoqués par ces derniers à chaque mission qu’ils effectuent. Il s’agit de Fairy Tail. </p>
            <p>
                L’histoire se focalise principalement sur les missions effectuées par l’une des équipes de la guilde
                Fairy Tail,
                composée de
                <a href="characterDetails.php?characterId=2">
                    Natsu Dragneel
                </a>
                (chasseur de dragon de feu),
                <a href="characterDetails.php?characterId=4">Lucy Heartfilia</a> (constellationniste) et
                <a href="characterDetails.php?characterId=3">Happy</a>
                (un chat bleu Exceed pouvant se faire pousser des ailes, voler et parler), qui seront très vite
                rejoints
                par
                <a href="characterDetails.php?characterId=8">Erza Scarlett</a> (mage chevalier) et
                <a href="characterDetails.php?characterId=5">Grey Fullbuster</a> (Mage de glaces puis plus tard
                Chasseur de démons de
                Glace),
                deux autres membres de la fameuse guilde. Ils sont rejoints au cours de l'aventure par
                <a href="characterDetails.php?characterId=9">Carla</a> (un chat
                blanc
                Exceed, comme Happy), <a href="characterDetails.php?characterId=7">Wendy</a> (chasseuse de dragon
                céleste), et par bien d'autres.
            </p>
            <p>Les principaux faits marquants de l’histoire sont l’apparition du dragon noir de l’apocalypse
                Acnologia
                et la
                biostasie des membres de Fairy Tail sur l’île Tenrô.

                Depuis la disparition de tous les dragons le 7 juillet 777, c’est la première fois qu’un dragon
                refait
                son
                apparition au vu de tous (excepté lors de l’arc Daphné exclusif à l’anime).

                Quant à la biostasie des membres de Fairy Tail, elle a été causée par l’attaque de l’île Tenrô par
                le
                dragon
                Acnologia. Son attaque est assez puissante pour détruire l’intégralité de l’île ainsi que tous les
                membres
                de Fairy Tail présents sur place. Pour protéger l’île et les membres de l’attaque, <a
                        href="characterDetails.php?characterId=1">Mavis Vermillion</a>,
                premier
                maître de Fairy Tail, a lancé un des trois sorts légendaires de la guilde, Fairy Sphere, pour créer
                un
                bouclier
                protecteur autour de l’île. Malgré la disparition de l’île, l’utilisation de ce sort a plongé l’île
                et
                ses
                occupants dans un sommeil prolongé de sept ans sans subir la vieillesse, tandis que les autres
                membres
                de la
                guilde et le reste de la population ont continué de vivre normalement. </p>
        </article>
    </section>
    <section class="comicsAndMovies">
        <article class="comics">
            <h2>Liste des Chapitres du manga</h2>
            <ul>
                <li>1: Arc Macao (chapitres 1 à 3)</li>
                <li>2: Arc Day Break (chapitres 4 à 9)</li>
                <li>3: Arc Eisen Wald (chapitres 10 à 21)</li>
                <li>4: Arc Île de Galuna (chapitres 22 à 46)</li>
                <li>5: Arc Phantom Lord (chapitres 47 à 68)</li>
                <li>6: Arc Loki (chapitres 69 à 74)</li>
                <li>7: Arc Tour du paradis (chapitres 75 à 105)</li>
                <li>8: Arc Battle of Fairy Tail (chapitres 106 à 129)</li>
                <li>9: Arc Oracion Seis (chapitres 130 à 165)</li>
                <li>10: Arc Edolas (chapitres 166 à 200)</li>
                <li>11: Arc Île Tenrô (chapitres 201 à 253)</li>
                <li>12: Arc Sept ans plus tard (chapitres 254 à 257)</li>
                <li>13: Arc Grands Jeux Magiques (chapitres 258 à 322)</li>
                <li>14: Arc Eclipse (chapitres 323 à 340)</li>
                <li>15: Arc Village du Soleil (chapitres 341 à 355)</li>
                <li>16: Arc Tartaros (chapitres 356 à 417)</li>
                <li>17: Arc Avatar (chapitres 418 à 435)</li>
                <li>18: Arc Arbaless (chapitres 436 à 545)</li>
                <li>19: Arc La Quête de 100 ans (Fairy Tail 100 Years Quest chapitres 1 à ???)
                    <ul>
                        <li>19.1: Sous-Arc Le Dragon Divin de l'Eau (Fairy Tail 100 Years Quest chapitres 1 à 24)
                        </li>
                        <li>19.2: Sous-Arc Le Dragon Divin du Bois (Fairy Tail 100 Years Quest chapitres 25 à ???)
                        </li>
                    </ul>
                </li>
            </ul>
        </article>
        <article class="anime">
            <h2>Liste des Chapitres de l'animation</h2>
            <ul>
                <li class="season">Saison 1
                    <ul>
                        <li>1: Arc Macao (épisodes 1 et 2)</li>
                        <li>2: Arc Day Break (épisodes 3 et 4)</li>
                        <li>3: Arc Eisen Wald (épisodes 5 à 9)</li>
                        <li>4: Arc Île de Galuna (épisodes 10 à 18)</li>
                        <li>5: Arc Phantom Lord (épisodes 19 à 29)</li>
                        <li>6: Arc Loki (épisodes 30 à 32)</li>
                        <li>7: Arc Tour du paradis (épisodes 33 à 41)</li>
                        <li>8: Arc Battle of Fairy Tail (épisodes 42 à 48)</li>
                    </ul>
                </li>
                <li class="season">Saison 2
                    <ul>
                        <li>1: Arc Oracion Seis (épisodes 49 à 68)</li>
                        <li>2: Arc Daphné (épisodes 69 à 72)</li>
                        <li>3: Arc Edolas (épisodes 73 à 95)</li>
                    </ul>
                <li class="season">Saison 3
                    <ul>
                        <li>1: Arc Île Tenrô (épisodes 96 à 122)</li>
                        <li>2: Arc Sept ans plus tard (épisodes 123 et 124)</li>
                        <li>3: Arc La clé du ciel étoilé (épisodes 125 à 150)</li>
                    </ul>
                <li class="season">Saison 4
                    <ul>
                        <li>1: Arc Grands Jeux Inter-Magiques (épisodes 151 à 175)</li>
                    </ul>
                <li class="season">Saison 5
                    <ul>
                        <li>1: Arc Éclipse (épisodes 176 à 201)</li>
                        <li>2: Arc Éclipse des esprits stellaires (épisodes 202 à 218)</li>
                        <li>3: Arc La Créature Mystérieuse (épisodes 219 à 226)</li>
                    </ul>
                <li class="season">Saison 6
                    <ul>
                        <li>1: Arc Village du Soleil (épisodes 227 à 233)</li>
                        <li>2: Arc Tartaros (épisodes 234 à 265)</li>
                        <li>3: Arc Fairy Tail Zérø (épisodes 266 à 275)</li>
                        <li>4: Arc Un an plus tard (épisodes 276 et 277)</li>
                    </ul>
                <li class="season">Saison 7
                    <ul>
                        <li>1: Arc Avatar (épisodes 278 à 284)</li>
                        <li>2: Arc Arbaless (épisodes 285 à 328)</li>
                    </ul>
                </li>
            </ul>
        </article>
        <article class="oav">
            <h2>Liste des OAV</h2>
            <ul>
                <li><b>Bienvenue à Fairy Hills !!</b> (15 avril 2011)</li>
                <li><b>L’Académie des fées : Le Délinquant et la Délinquante</b> (17 juin 2011)</li>
                <li><b>Memory Days</b> (17 février 2012)</li>
                <li><b>Le Camp d’entraînement des fées</b> (16 novembre 2012)</li>
                <li><b>Loisirs d’été à Ryûzetsu Land</b> (17 juin 2013)</li>
                <li><b>Fairy Tail x Rave</b> (16 août 2013)</li>
                <li><b>Le châtiment des Fées</b> (17 mai 2016)</li>
                <li><b>Natsu vs Mavis</b> (17 novembre 2016)</li>
                <li><b>Fairy Christmas</b> (16 décembre 2016)</li>
            </ul>
        </article>
        <article class="movies">
            <h2>Liste des Films</h2>
            <ul>
                <li><b>Fairy Tail, le film : La prêtresse du Phœnix</b> (28 août 2013)</li>
                <li><b>Fairy Tail, le film : Dragon Cry</b> (6 mai 2017)</li>
            </ul>
        </article>
    </section>
    <section class="videoGames">
        <article class="games">
            <h2>Liste des jeux vidéo sur Fairy tail</h2>
            <ul>
                <li><b>2009 : Sunday VS Magazine: Shūketsu! Chōjō Daikessen </b> sorti sur PlayStation Portable
                    (jeu vidéo de type crossover)79
                </li>
                <li><b>2010 : Fairy Tail: Portable Guild </b>sorti sur PlayStation Portable80</li>
                <li><b>2010 : TV Anime Fairy Tail: Gekitô! Madôshi Kessenn </b> sorti sur Nintendo DS81</li>
                <li><b>2011 : Fairy Tail: Portable Guild 2 </b>sorti sur PlayStation Portable82</li>
                <li><b>2011 : Original story from Fairy Tail </b>sorti sur Nintendo DS83</li>
                <li><b>2012 : Fairy Tail: Zeref Awakens </b>sorti sur PlayStation Portable84</li>
                <li><b>2014 : Fairy Tail: Brave Saga </b>sorti sur iOS et Android au Japon</li>
                <li><b>2015 : Fairy Tail: Goku Mahou Ranbu </b>sorti sur iOS et Android au Japon/li>
                <li><b>2017 : Fairy Tail: Hero's Journey </b>sorti sur Navigateur disponible dans tous les pays</li>
                <li><b>2019 : Fairy Tail: Dice Magic </b>sorti sur iOS et Android au Japon</li>
                <li><b>2020 : Fairy Tail, </b>sorti sur Playstation 4, Switch et Steam</li>
            </ul>
        </article>
    </section>
    <section class="openings">
        <article class="music">
            <h2>Liste des Openings de Fairy tail</h2>
            <p>Les Openings sont les musiques d'introduction de l'épisode</p>
            <ul>
                <li><a href="https://www.youtube.com/watch?v=8EMCTHpRnJE" target="_blank">Snow Fairy</a>, épisode 1
                    à 11
                </li>
                <li><a href="https://www.youtube.com/watch?v=ITpSB6oESTs" target="_blank">S.O.W. Sense Of Wonder</a>,
                    épisode 12 à 24
                </li>
                <li><a href="https://www.youtube.com/watch?v=T60pzAKu60Q" target="_blank">ft.</a>, épisode 25 à 35
                </li>
                <li><a href="https://www.youtube.com/watch?v=pBjEG5azuNY" target="_blank">R.P.G.~Rockin' Playing
                        Game</a>, épisode 26 à 48
                </li>
                <li><a href="https://www.youtube.com/watch?v=zKI4LLWMrdI" target="_blank">Egao no Mahou</a>, épisode
                    48 à 60
                </li>
                <li><a href="https://www.youtube.com/watch?v=FwHU32HL3SE" target="_blank">Fiesta</a>, épisode 61 à
                    72
                </li>
                <li><a href="https://www.youtube.com/watch?v=gyK5t1D4anQ" target="_blank">Evidence</a>, épisode 73 à
                    85
                </li>
                <li><a href="https://www.youtube.com/watch?v=aVMUbTT-acI" target="_blank">The Rock City Boy</a>,
                    épisode 86 à 98
                </li>
                <li><a href="https://www.youtube.com/watch?v=QlazhMnDpc8" target="_blank">Towa no Kizuna feat.
                        Another Infinity</a>, épisode 99 à 111
                </li>
                <li><a href="https://www.youtube.com/watch?v=ahJ-gCPy2OQ" target="_blank">I Wish</a>, épisode 112 à
                    124
                </li>
                <li><a href="https://www.youtube.com/watch?v=nSuYPS4HiWQ" target="_blank">Hajimari no Sora</a>,
                    épisode 125 à 137
                </li>
                <li><a href="https://www.youtube.com/watch?v=R5sa0Yl8RVU" target="_blank">Tenohira</a>, épisode 138
                    à 150
                </li>
                <li><a href="https://www.youtube.com/watch?v=KGr45sK-F_Q" target="_blank">Breakthrough</a>, épisode
                    151 à 166
                </li>
                <li><a href="https://www.youtube.com/watch?v=1wdp7Ndnpxw" target="_blank">Fairy Tail ~Yakusoku no
                        Hi~</a>, épisode 167 à 175
                </li>
                <li><a href="https://www.youtube.com/watch?v=bhjBqzeIy2k" target="_blank">MASAYUME CHASING</a>,
                    épisode 176 à 188
                </li>
                <li><a href="https://www.youtube.com/watch?v=Tb_0Y-gZ2tk" target="_blank">STRIKE BACK</a>, épisode
                    189 à 203
                </li>
                <li><a href="https://www.youtube.com/watch?v=qpvkFgW109I" target="_blank">Mysterious Magic</a>,
                    épisode 204 à 214
                </li>
                <li><a href="https://www.youtube.com/watch?v=6vfucB0hcbA" target="_blank">break out</a>, épisode 215
                    à 226
                </li>
                <li><a href="https://www.youtube.com/watch?v=4WaiLBHWi4s" target="_blank">Yumeiro Graffiti</a>,
                    épisode 227 à 239
                </li>
                <li><a href="https://www.youtube.com/watch?v=3nKD5sPumiA" target="_blank">NEVER-END TALE</a>,
                    épisode 240 à 252
                </li>
                <li><a href="https://www.youtube.com/watch?v=E0Kgs8edDpA" target="_blank">Believe in Myself</a>,
                    épisode 253 à 265
                </li>
                <li><a href="https://www.youtube.com/watch?v=e-7uuV7B7mo" target="_blank">Ashita Wo Narase</a>,
                    épisode 266 à 277
                </li>
                <li><a href="https://www.youtube.com/watch?v=hA5P15f8i9I" target="_blank">Power of the Dream</a>,
                    épisode 278 à 290
                </li>
                <li><a href="https://www.youtube.com/watch?v=bGTnzHajLAw" target="_blank">DOWN BY LAW</a>, épisode
                    291 à 303
                </li>
                <li><a href="https://www.youtube.com/watch?v=IZfG1M_Ona4" target="_blank">NO-LIMIT</a>, épisode 304
                    à 315
                </li>
                <li><a href="https://www.youtube.com/watch?v=lgd3pCE3rMY" target="_blank">MORE THAN LiKE</a>,
                    épisode 316 à 328
                </li>
            </ul>
        </article>
    </section>
    <section class="endings">
        <article class="music">
            <h2>Liste des Endings de Fairy tail</h2>
            <p>Les Endings sont les musiques de fin des épisodes</p>
            <ul>
                <li><a href="https://www.youtube.com/watch?v=QlazhMnDpc8" target="_blank">Kanpekigu No Ne</a>,
                    épisode 1 à 11
                </li>
                <li><a href="https://www.youtube.com/watch?v=tbJtDRlsGEU" target="_blank">Tsuioku Merry-Go-Round</a>,
                    épisode 12 à 24
                </li>
                <li><a href="https://www.youtube.com/watch?v=wvIHHZdTJpY" target="_blank">Gomen ne, watashi</a>,
                    épisode 25 à 35
                </li>
                <li><a href="https://www.youtube.com/watch?v=Q8hEsz2KGpo" target="_blank">Kimi ga Iru Kara</a>,
                    épisode 26 à 48
                </li>
                <li><a href="https://www.youtube.com/watch?v=bmdyyLxg1rU" target="_blank">HOLY SHINE</a>, épisode 48
                    à 60
                </li>
                <li><a href="https://www.youtube.com/watch?v=UWPu8bJGIdQ" target="_blank">Be As One</a>, épisode 61
                    à 72
                </li>
                <li><a href="https://www.youtube.com/watch?v=gstP23ek_rg" target="_blank">Lonely Person</a>, épisode
                    73 à 85
                </li>
                <li><a href="https://www.youtube.com/watch?v=QY04WPLTGbc" target="_blank">Don't think. Feel!!!</a>,
                    épisode 86 à 98
                </li>
                <li><a href="https://www.youtube.com/watch?v=ihQUYUM9tG8" target="_blank">Kono Te Nobashite</a>,
                    épisode 99 à 111
                </li>
                <li><a href="https://www.youtube.com/watch?v=eS7aLmjGZ1E" target="_blank">Boys Be Ambitious!!</a>,
                    épisode 112 à 124
                </li>
                <li><a href="https://www.youtube.com/watch?v=4th6kG1ZBco" target="_blank">Glitter (Starving Trancer
                        Remix)</a>, épisode 125 à 137
                </li>
                <li><a href="https://www.youtube.com/watch?v=Q0zhllQ3Nng" target="_blank">Yell ~Kagayaku Tame no
                        Mono~</a>, épisode 138 à 150
                </li>
                <li><a href="https://www.youtube.com/watch?v=nDO7r8otNPw" target="_blank">Kimi ga Kureta Mono</a>,
                    épisode 151 à 166
                </li>
                <li><a href="https://www.youtube.com/watch?v=SXqdT5kOIAw" target="_blank">We're the stars</a>,
                    épisode 167 à 175
                </li>
                <li><a href="https://www.youtube.com/watch?v=yQkS3nainSw" target="_blank">Kimi to Kare to Boku to
                        Kanojo to</a>, épisode 176 à 188
                </li>
                <li><a href="https://www.youtube.com/watch?v=pdrf49wtdNs" target="_blank">Kokoro no Kagi</a>,
                    épisode 189 à 203
                </li>
                <li><a href="https://www.youtube.com/watch?v=Lp-rOWpMzGY" target="_blank">Kimi no Mirai</a>, épisode
                    204 à 214
                </li>
                <li><a href="https://www.youtube.com/watch?v=0cgZYvGOMVs" target="_blank">Don't let me down</a>,
                    épisode 215 à 226
                </li>
                <li><a href="https://www.youtube.com/watch?v=fhvDyO9vuew" target="_blank">Never ever</a>, épisode
                    227 à 239
                </li>
                <li><a href="https://www.youtube.com/watch?v=EBnkVcb4eTI" target="_blank">FOREVER HERE</a>, épisode
                    240 à 252
                </li>
                <li><a href="https://www.youtube.com/watch?v=ZNXSOj66Mfs" target="_blank">Azayaka na Tabiji</a>,
                    épisode 253 à 265
                </li>
                <li><a href="https://www.youtube.com/watch?v=1wdcg78-Lp0" target="_blank">Landscape</a>, épisode 266
                    à 277
                </li>
                <li><a href="https://www.youtube.com/watch?v=ukuFXcSW-JY" target="_blank">Endless Harmony</a>,
                    épisode 278 à 290
                </li>
                <li><a href="https://www.youtube.com/watch?v=ZmVNhgkgtXo" target="_blank">Pierce</a>, épisode 291 à
                    303
                </li>
                <li><a href="https://www.youtube.com/watch?v=TB8CE_mW2MA" target="_blank">Boku to Kimi no
                        Lullaby</a>, épisode 304 à 315
                </li>
                <li><a href="https://www.youtube.com/watch?v=dnR6aoZlTfQ" target="_blank">Exceed (Ending)</a>,
                    épisode 316 à 328
                </li>
            </ul>
        </article>
    </section>
</main>