<section class="primaryButton">
    <a class="btn btn-primary home" href="<?= PATH_URI ?>masterOfGuilde/index.php"><i class="fas fa-home"></i> Home admin </a>
    <a class="btn btn-success" href="<?= PATH_URI ?>masterOfGuilde/addCharacter.php" id="addCharacterButton"><i class="fas fa-plus"></i> Ajouter</a>
    <a class="btn btn-info" href="<?= PATH_URI ?>masterOfGuilde/editCharacter.php" id="editCharacterButton"><i class="fas fa-edit"></i> Modifier / Supprimer</a>
</section>