<?php include "$button.phtml" ?>
<section class="editSearch">
    <button class="btn-info toggleListCharacter">Afficher/cacher liste des personnages</button>
</section>

<section class="sectionEdit hide">
    <h2>Pour modifier un personnage, Cliquez sur son nom !</h2>
    <p>Les personnages sont trier par ordre Alphabétique de leur prénom A-Z !</p>
    <?php foreach ($characters as $character): ?>
        <div>
            <img src="<?= $character['photo'] ?>" alt="<?= htmlspecialchars($character['characterName']) ?>">
            <a href="editPage.php?id=<?= intval($character['characterId']) ?>">
                <?= htmlspecialchars($character['characterName']) ?>
            </a>
        </div>
    <?php endforeach ?>
    <a href="editCharacter.php" class="btn-info">Haut de page</a>
</section>