<body>
<section class="masterOfGuild">
    <h1>
        <img src="<?= PATH_URI ?>public/images/fairy-tail-logo-png-7-transparent.png" alt="Logo SVG de la guilde Fairy Tail">
        Administration de la Guilde
        <img src="<?= PATH_URI ?>public/images/fairy-tail-logo-png-7-transparent.png" alt="Logo SVG de la guilde Fairy Tail">
    </h1>
    <?php include "$button.phtml"?>
    <section class="adminDescription">
        <h2>Seuls les administrateurs de la Guilde ont accés a cette page</h2>
        <p>Sur cette page, vous pouvez Ajouter un personnage, Modifier un personnage ou encore Supprimer un personnage.</p>
    </section>
</section>
</body>
